-- See Capstone spec/simple/requirements.md "Domain" for the schema description.
-- Money is NUMBER(19,4) and maps to BigDecimal in Java. Never double.

CREATE TABLE BANK_USERS (
    USER_ID         VARCHAR2(64)   NOT NULL,
    SUBJECT         VARCHAR2(255)  NOT NULL,
    EMAIL           VARCHAR2(255)  NOT NULL,
    DISPLAY_NAME    VARCHAR2(255),
    ROLE            VARCHAR2(16)   NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BANK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_BANK_USERS_SUBJECT UNIQUE (SUBJECT),
    CONSTRAINT CK_BANK_USERS_ROLE CHECK (ROLE IN ('CUSTOMER','ADMIN'))
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID      VARCHAR2(64)   NOT NULL,
    OWNER_ID        VARCHAR2(64)   NOT NULL,
    ACCOUNT_TYPE    VARCHAR2(16)   NOT NULL,
    CURRENCY        VARCHAR2(3)    DEFAULT 'USD' NOT NULL,
    BALANCE         NUMBER(19, 4)  DEFAULT 0     NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNTS_OWNER FOREIGN KEY (OWNER_ID) REFERENCES BANK_USERS(USER_ID),
    CONSTRAINT CK_ACCOUNTS_TYPE CHECK (ACCOUNT_TYPE IN ('CHECKING','SAVINGS')),
    CONSTRAINT CK_ACCOUNTS_BALANCE CHECK (BALANCE >= 0)
);

CREATE INDEX IX_ACCOUNTS_OWNER ON ACCOUNTS (OWNER_ID);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID      VARCHAR2(64)   NOT NULL,
    ACCOUNT_ID          VARCHAR2(64)   NOT NULL,
    TYPE                VARCHAR2(16)   NOT NULL,
    AMOUNT              NUMBER(19, 4)  NOT NULL,
    STATUS              VARCHAR2(16)   NOT NULL,
    COUNTERPARTY        VARCHAR2(64),
    TRANSFER_GROUP_ID   VARCHAR2(64),
    DESCRIPTION         VARCHAR2(255),
    CREATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_TRANSACTIONS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID),
    CONSTRAINT CK_TRANSACTIONS_TYPE CHECK (TYPE IN ('DEPOSIT','WITHDRAWAL','TRANSFER_OUT','TRANSFER_IN')),
    CONSTRAINT CK_TRANSACTIONS_STATUS CHECK (STATUS IN ('PENDING','COMPLETED','FAILED')),
    CONSTRAINT CK_TRANSACTIONS_AMOUNT CHECK (AMOUNT > 0)
);

CREATE INDEX IX_TRANSACTIONS_ACCOUNT_CREATED
    ON TRANSACTIONS (ACCOUNT_ID, CREATED_AT DESC);

CREATE INDEX IX_TRANSACTIONS_GROUP
    ON TRANSACTIONS (TRANSFER_GROUP_ID);
